export const MUTATIONS = {
  auth: {
    updateAtion: "updateAction",
    toggleShowAlert: "toggleShowAlert",
    updateMobileLoginForm: "updateMobileLoginForm",
    updatePasswordLoginForm: "updatePasswordLoginForm",
    updateMobileRegisterForm: "updateMobileRegisterForm",
    updatePasswordRegisterForm: "updatePasswordRegisterForm",
    setResponseText: "setResponseText",
    updateMobileResendCode: "updateMobileResendCode",
    updateCodeVerifyCode: "updateCodeVerifyCode",
    updatePasswordResetPassword: "updatePasswordResetPassword",
    updateConfirmResetPassword: "updateConfirmResetPassword",
    clearDataLoginForm: "clearDataLoginForm",
    clearDataRegisterForm: "clearDataRegisterForm",
  },
  app: {
    app: "app",
    toggleSidebarColor: "toggleSidebarColor",
    toggleConfigurator: "toggleConfigurator",
    toggleShowNavbar: "toggleShowNavbar",
    toggleShowBillsList: "toggleShowBillsList",
    toggleShowSidebarOff: "toggleShowSidebarOff",
    toggleShowSidebarOn: "toggleShowSidebarOn",
    navbarMinimize: "navbarMinimize",
    toggleShowSidebar: "toggleShowSidebar",
    toggleOffShowNavbar: "toggleOffShowNavbar",
    toggleOnShowNavbar: "toggleOnShowNavbar",
    toggleLoadingApp: "toggleLoadingApp",
    getBgSidebar: "getBgSidebar",
    toggleDisabledButtonTrue: "toggleDisabledButtonTrue",
    toggleDisabledButtonOff: "toggleDisabledButtonOff",
    toggleSidebarMobile: "toggleSidebarMobile",
  },

  panel: {
    showChargeTypeMci: "showChargeTypeMci",
    showChargeTypeMtn: "showChargeTypeMtn",
    showChargeTypeRightel: "showChargeTypeRightel",
    setAmountByCharge: "setAmountByCharge",
    setOperatorByCharge: "SetOperatorByCharge",
    updateMobileReCharge: "updateMobileReCharge",
    setReChargeCodeByCharge: "setReChargeCodeByCharge",
    toggleReCharge: "toggleReCharge",
    billingLogoSelecting: "billingLogoSelecting",
    billTitleSelecting: "billTitleSelecting",
    setNameInternetPackageType: "setNameInternetPackageType",
    setOperatorInternetPackageType: "setOperatorInternetPackageType",
    submitRechargeForm: "submitRechargeForm",
    setPlaceholderBillSelecting: "setPlaceholderBillSelecting",
    setIdBilling: "setIdBilling",
    setIsActiveBilling: "setIsActiveBilling",
    setOperatorBilling: "setOperatorBilling",
    setLogoInternetPackage: "setLogoInternetPackage",
    selectInternetType: "selectInternetType",
    clearDataChargeInput: "clearDataChargeInput",
    pushInternetPackageList: "pushInternetPackageList",
  },
};
